#!/bin/sh

set -ex

# DPHHOME should point to the root of the repo
DPMHOME=${DPMHOME:-$(pwd)}
# SMS1 is the hostname of master node 1 of the shasta-vm craystack cluster
SMS1=${SMS1:-ncn-m001.craystack.test}
# Name of the chart
CHART=${CHART:-dws-operator}
# VMHOME should point to the root of the shasta-vm repo used to build the craystack cluster
VMHOME=${VMHOME:-$HOME/stash/shasta-vm}

pushd ${DPMHOME}/kubernetes/${CHART}

error_exit()
{
	popd
	exit 1
}

# Package helm chart locally
rm -fr /tmp/${CHART}/pkgs
mkdir -p /tmp/${CHART}/pkgs
helm package -u -d /tmp/${CHART}/pkgs . || error_exit

# Sync packaged charts to remote system
ssh root@${SMS1} mkdir -p /root/loftsman/${CHART}/charts
rsync -av --progress /tmp/${CHART}/pkgs/ root@${SMS1}:/root/loftsman/${CHART}/charts/

# Sync Loftsman manifest
rsync -avz --progress ${DPMHOME}/test/loftsman/loftsman-manifest.yaml root@${SMS1}:/root/loftsman/${CHART}/loftsman-manifest.yaml

# Sync Loftsman cleanup scripts
rsync -avz --progress ${DPMHOME}/test/loftsman/loftsman-delete* root@${SMS1}:/root/loftsman/${CHART}

# Run Loftsman playbook
ansible-playbook -vvv --vault-password-file ${VMHOME}/workspace/ansible-inventories/craystack/.vault.txt \
	-i ${VMHOME}/workspace/ansible-inventories/craystack/inventory.ini \
    --extra-vars '{"packaged_charts_path": "/root/loftsman/dws-operator/charts", "loftsman_manifest_file_path": "/root/loftsman/dws-operator/loftsman-manifest.yaml", "is_craystack_or_cmsbasebox": false, "docker_registry": "dtr.dev.cray.com"}' \
    ${VMHOME}/workspace/loftsman-deploy/ansible_framework/main_loftsman.yaml

popd
