apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: webhook
        env:
        - name: ENVIRONMENT
          value: "craystack"
