apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ index .Values "cray-service" "serviceAccountName" }}
  labels:
    app.kubernetes.io/name: {{ include "cray-service.name" . }}
    {{- include "cray-service.common-labels" . | nindent 4 }}
  annotations:
    {{- include "cray-service.common-annotations" . | nindent 4 }}
