apiVersion: v1
kind: Service
metadata:
  name: {{ include "dws-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: dws-operator
  ports:
    - port: 443
      targetPort: 9443
