/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	dwsv1alpha1 "stash.us.cray.com/dpm/dws-operator/pkg/apis/dws/v1alpha1"
	versioned "stash.us.cray.com/dpm/dws-operator/pkg/client/clientset/versioned"
	internalinterfaces "stash.us.cray.com/dpm/dws-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "stash.us.cray.com/dpm/dws-operator/pkg/client/listers/dws/v1alpha1"
)

// DriverInformer provides access to a shared informer and lister for
// Drivers.
type DriverInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DriverLister
}

type driverInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDriverInformer constructs a new informer for Driver type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDriverInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDriverInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDriverInformer constructs a new informer for Driver type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDriverInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DwsV1alpha1().Drivers(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DwsV1alpha1().Drivers(namespace).Watch(options)
			},
		},
		&dwsv1alpha1.Driver{},
		resyncPeriod,
		indexers,
	)
}

func (f *driverInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDriverInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *driverInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&dwsv1alpha1.Driver{}, f.defaultInformer)
}

func (f *driverInformer) Lister() v1alpha1.DriverLister {
	return v1alpha1.NewDriverLister(f.Informer().GetIndexer())
}
