apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: system
  labels:
    control-plane: webhook
spec:
  selector:
    matchLabels:
      control-plane: webhook
  replicas: 3
  template:
    metadata:
      labels:
        control-plane: webhook
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: control-plane
                operator: In
                values:
                - webhook
            topologyKey: "kubernetes.io/hostname"
      securityContext:
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - --mode=webhook
        image: controller:latest
        name: webhook
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 25
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 60Mi
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-cert
      serviceAccountName: webhook
      terminationGracePeriodSeconds: 10
