/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "stash.us.cray.com/dpm/dws-operator/pkg/apis/dws/v1alpha1"
)

// FakeDWDirectiveRuleDeves implements DWDirectiveRuleDefInterface
type FakeDWDirectiveRuleDeves struct {
	Fake *FakeDwsV1alpha1
	ns   string
}

var dwdirectiveruledevesResource = schema.GroupVersionResource{Group: "dws.cray.com", Version: "v1alpha1", Resource: "dwdirectiveruledeves"}

var dwdirectiveruledevesKind = schema.GroupVersionKind{Group: "dws.cray.com", Version: "v1alpha1", Kind: "DWDirectiveRuleDef"}

// Get takes name of the dWDirectiveRuleDef, and returns the corresponding dWDirectiveRuleDef object, and an error if there is any.
func (c *FakeDWDirectiveRuleDeves) Get(name string, options v1.GetOptions) (result *v1alpha1.DWDirectiveRuleDef, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dwdirectiveruledevesResource, c.ns, name), &v1alpha1.DWDirectiveRuleDef{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DWDirectiveRuleDef), err
}

// List takes label and field selectors, and returns the list of DWDirectiveRuleDeves that match those selectors.
func (c *FakeDWDirectiveRuleDeves) List(opts v1.ListOptions) (result *v1alpha1.DWDirectiveRuleDefList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dwdirectiveruledevesResource, dwdirectiveruledevesKind, c.ns, opts), &v1alpha1.DWDirectiveRuleDefList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DWDirectiveRuleDefList), err
}

// Watch returns a watch.Interface that watches the requested dWDirectiveRuleDeves.
func (c *FakeDWDirectiveRuleDeves) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dwdirectiveruledevesResource, c.ns, opts))

}

// Create takes the representation of a dWDirectiveRuleDef and creates it.  Returns the server's representation of the dWDirectiveRuleDef, and an error, if there is any.
func (c *FakeDWDirectiveRuleDeves) Create(dWDirectiveRuleDef *v1alpha1.DWDirectiveRuleDef) (result *v1alpha1.DWDirectiveRuleDef, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dwdirectiveruledevesResource, c.ns, dWDirectiveRuleDef), &v1alpha1.DWDirectiveRuleDef{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DWDirectiveRuleDef), err
}

// Update takes the representation of a dWDirectiveRuleDef and updates it. Returns the server's representation of the dWDirectiveRuleDef, and an error, if there is any.
func (c *FakeDWDirectiveRuleDeves) Update(dWDirectiveRuleDef *v1alpha1.DWDirectiveRuleDef) (result *v1alpha1.DWDirectiveRuleDef, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dwdirectiveruledevesResource, c.ns, dWDirectiveRuleDef), &v1alpha1.DWDirectiveRuleDef{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DWDirectiveRuleDef), err
}

// Delete takes name of the dWDirectiveRuleDef and deletes it. Returns an error if one occurs.
func (c *FakeDWDirectiveRuleDeves) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dwdirectiveruledevesResource, c.ns, name), &v1alpha1.DWDirectiveRuleDef{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDWDirectiveRuleDeves) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dwdirectiveruledevesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.DWDirectiveRuleDefList{})
	return err
}

// Patch applies the patch and returns the patched dWDirectiveRuleDef.
func (c *FakeDWDirectiveRuleDeves) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DWDirectiveRuleDef, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dwdirectiveruledevesResource, c.ns, name, pt, data, subresources...), &v1alpha1.DWDirectiveRuleDef{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DWDirectiveRuleDef), err
}
