/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "stash.us.cray.com/dpm/dws-operator/pkg/apis/dws/v1alpha1"
)

// FakeDWDirectiveRules implements DWDirectiveRuleInterface
type FakeDWDirectiveRules struct {
	Fake *FakeDwsV1alpha1
	ns   string
}

var dwdirectiverulesResource = schema.GroupVersionResource{Group: "dws.cray.hpe.com", Version: "v1alpha1", Resource: "dwdirectiverules"}

var dwdirectiverulesKind = schema.GroupVersionKind{Group: "dws.cray.hpe.com", Version: "v1alpha1", Kind: "DWDirectiveRule"}

// Get takes name of the dWDirectiveRule, and returns the corresponding dWDirectiveRule object, and an error if there is any.
func (c *FakeDWDirectiveRules) Get(name string, options v1.GetOptions) (result *v1alpha1.DWDirectiveRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dwdirectiverulesResource, c.ns, name), &v1alpha1.DWDirectiveRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DWDirectiveRule), err
}

// List takes label and field selectors, and returns the list of DWDirectiveRules that match those selectors.
func (c *FakeDWDirectiveRules) List(opts v1.ListOptions) (result *v1alpha1.DWDirectiveRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dwdirectiverulesResource, dwdirectiverulesKind, c.ns, opts), &v1alpha1.DWDirectiveRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DWDirectiveRuleList{ListMeta: obj.(*v1alpha1.DWDirectiveRuleList).ListMeta}
	for _, item := range obj.(*v1alpha1.DWDirectiveRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dWDirectiveRules.
func (c *FakeDWDirectiveRules) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dwdirectiverulesResource, c.ns, opts))

}

// Create takes the representation of a dWDirectiveRule and creates it.  Returns the server's representation of the dWDirectiveRule, and an error, if there is any.
func (c *FakeDWDirectiveRules) Create(dWDirectiveRule *v1alpha1.DWDirectiveRule) (result *v1alpha1.DWDirectiveRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dwdirectiverulesResource, c.ns, dWDirectiveRule), &v1alpha1.DWDirectiveRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DWDirectiveRule), err
}

// Update takes the representation of a dWDirectiveRule and updates it. Returns the server's representation of the dWDirectiveRule, and an error, if there is any.
func (c *FakeDWDirectiveRules) Update(dWDirectiveRule *v1alpha1.DWDirectiveRule) (result *v1alpha1.DWDirectiveRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dwdirectiverulesResource, c.ns, dWDirectiveRule), &v1alpha1.DWDirectiveRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DWDirectiveRule), err
}

// Delete takes name of the dWDirectiveRule and deletes it. Returns an error if one occurs.
func (c *FakeDWDirectiveRules) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dwdirectiverulesResource, c.ns, name), &v1alpha1.DWDirectiveRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDWDirectiveRules) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dwdirectiverulesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.DWDirectiveRuleList{})
	return err
}

// Patch applies the patch and returns the patched dWDirectiveRule.
func (c *FakeDWDirectiveRules) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DWDirectiveRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dwdirectiverulesResource, c.ns, name, pt, data, subresources...), &v1alpha1.DWDirectiveRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DWDirectiveRule), err
}
