/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "stash.us.cray.com/dpm/dws-operator/pkg/apis/dws/v1alpha1"
)

// FakeWorkflowSpecs implements WorkflowSpecInterface
type FakeWorkflowSpecs struct {
	Fake *FakeDwsV1alpha1
	ns   string
}

var workflowspecsResource = schema.GroupVersionResource{Group: "dws.cray.com", Version: "v1alpha1", Resource: "workflowspecs"}

var workflowspecsKind = schema.GroupVersionKind{Group: "dws.cray.com", Version: "v1alpha1", Kind: "WorkflowSpec"}

// Get takes name of the workflowSpec, and returns the corresponding workflowSpec object, and an error if there is any.
func (c *FakeWorkflowSpecs) Get(name string, options v1.GetOptions) (result *v1alpha1.WorkflowSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(workflowspecsResource, c.ns, name), &v1alpha1.WorkflowSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkflowSpec), err
}

// List takes label and field selectors, and returns the list of WorkflowSpecs that match those selectors.
func (c *FakeWorkflowSpecs) List(opts v1.ListOptions) (result *v1alpha1.WorkflowSpecList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(workflowspecsResource, workflowspecsKind, c.ns, opts), &v1alpha1.WorkflowSpecList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkflowSpecList), err
}

// Watch returns a watch.Interface that watches the requested workflowSpecs.
func (c *FakeWorkflowSpecs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(workflowspecsResource, c.ns, opts))

}

// Create takes the representation of a workflowSpec and creates it.  Returns the server's representation of the workflowSpec, and an error, if there is any.
func (c *FakeWorkflowSpecs) Create(workflowSpec *v1alpha1.WorkflowSpec) (result *v1alpha1.WorkflowSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(workflowspecsResource, c.ns, workflowSpec), &v1alpha1.WorkflowSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkflowSpec), err
}

// Update takes the representation of a workflowSpec and updates it. Returns the server's representation of the workflowSpec, and an error, if there is any.
func (c *FakeWorkflowSpecs) Update(workflowSpec *v1alpha1.WorkflowSpec) (result *v1alpha1.WorkflowSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(workflowspecsResource, c.ns, workflowSpec), &v1alpha1.WorkflowSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkflowSpec), err
}

// Delete takes name of the workflowSpec and deletes it. Returns an error if one occurs.
func (c *FakeWorkflowSpecs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(workflowspecsResource, c.ns, name), &v1alpha1.WorkflowSpec{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWorkflowSpecs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(workflowspecsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.WorkflowSpecList{})
	return err
}

// Patch applies the patch and returns the patched workflowSpec.
func (c *FakeWorkflowSpecs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.WorkflowSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(workflowspecsResource, c.ns, name, pt, data, subresources...), &v1alpha1.WorkflowSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WorkflowSpec), err
}
