/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "stash.us.cray.com/dpm/dws-operator/pkg/apis/dws/v1alpha1"
)

// FakeDrivers implements DriverInterface
type FakeDrivers struct {
	Fake *FakeDwsV1alpha1
	ns   string
}

var driversResource = schema.GroupVersionResource{Group: "dws.cray.com", Version: "v1alpha1", Resource: "drivers"}

var driversKind = schema.GroupVersionKind{Group: "dws.cray.com", Version: "v1alpha1", Kind: "Driver"}

// Get takes name of the driver, and returns the corresponding driver object, and an error if there is any.
func (c *FakeDrivers) Get(name string, options v1.GetOptions) (result *v1alpha1.Driver, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(driversResource, c.ns, name), &v1alpha1.Driver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Driver), err
}

// List takes label and field selectors, and returns the list of Drivers that match those selectors.
func (c *FakeDrivers) List(opts v1.ListOptions) (result *v1alpha1.DriverList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(driversResource, driversKind, c.ns, opts), &v1alpha1.DriverList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DriverList{ListMeta: obj.(*v1alpha1.DriverList).ListMeta}
	for _, item := range obj.(*v1alpha1.DriverList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested drivers.
func (c *FakeDrivers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(driversResource, c.ns, opts))

}

// Create takes the representation of a driver and creates it.  Returns the server's representation of the driver, and an error, if there is any.
func (c *FakeDrivers) Create(driver *v1alpha1.Driver) (result *v1alpha1.Driver, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(driversResource, c.ns, driver), &v1alpha1.Driver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Driver), err
}

// Update takes the representation of a driver and updates it. Returns the server's representation of the driver, and an error, if there is any.
func (c *FakeDrivers) Update(driver *v1alpha1.Driver) (result *v1alpha1.Driver, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(driversResource, c.ns, driver), &v1alpha1.Driver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Driver), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDrivers) UpdateStatus(driver *v1alpha1.Driver) (*v1alpha1.Driver, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(driversResource, "status", c.ns, driver), &v1alpha1.Driver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Driver), err
}

// Delete takes name of the driver and deletes it. Returns an error if one occurs.
func (c *FakeDrivers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(driversResource, c.ns, name), &v1alpha1.Driver{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDrivers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(driversResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.DriverList{})
	return err
}

// Patch applies the patch and returns the patched driver.
func (c *FakeDrivers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Driver, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(driversResource, c.ns, name, pt, data, subresources...), &v1alpha1.Driver{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Driver), err
}
