# permissions for end users to view clientmounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clientmount-viewer-role
rules:
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - clientmounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - clientmounts/status
  verbs:
  - get
