# permissions for end users to edit clientmounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clientmount-editor-role
rules:
- apiGroups:
  - dws.dataworkflowservices.github.io
  resources:
  - clientmounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.dataworkflowservices.github.io
  resources:
  - clientmounts/status
  verbs:
  - get
