# permissions for end users to edit computes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: computes-editor-role
rules:
- apiGroups:
  - dws.dataworkflowservices.github.io
  resources:
  - computes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.dataworkflowservices.github.io
  resources:
  - computes/status
  verbs:
  - get
