# permissions for end users to view directivebreakdowns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: directivebreakdown-viewer-role
rules:
- apiGroups:
  - dws.dataworkflowservices.github.io
  resources:
  - directivebreakdowns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dws.dataworkflowservices.github.io
  resources:
  - directivebreakdowns/status
  verbs:
  - get
