# permissions for end users to edit dwdirectiverules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dwdirectiverule-editor-role
rules:
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - dwdirectiverules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - dwdirectiverules/status
  verbs:
  - get
