# permissions for end users to view persistentstorageinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: persistentstorageinstance-viewer-role
rules:
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - persistentstorageinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - persistentstorageinstances/status
  verbs:
  - get
