---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - clientmounts
  - systemconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - clientmounts/finalizers
  - systemconfigurations/finalizers
  - workflows/finalizers
  verbs:
  - update
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - clientmounts/status
  - systemconfigurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - computes
  - storages
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - dwdirectiverules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - workflows
  verbs:
  - get
  - list
  - patch
  - update
  - watch
