# permissions for end users to view servers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servers-viewer-role
rules:
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - servers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - servers/status
  verbs:
  - get
