# permissions for end users to view storagepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storagepool-viewer-role
rules:
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - storagepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - storagepools/status
  verbs:
  - get
