# permissions for end users to edit storagepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storagepool-editor-role
rules:
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - storagepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - storagepools/status
  verbs:
  - get
