# permissions for end users to view storages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storage-viewer-role
rules:
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - storages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dataworkflowservices.github.io
  resources:
  - storages/status
  verbs:
  - get
