# permissions for end users to edit systemconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: systemconfiguration-editor-role
rules:
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - systemconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - systemconfigurations/status
  verbs:
  - get
