---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-role
rules:
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - dwdirectiverules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dws.cray.hpe.com
  resources:
  - workflows
  verbs:
  - get
  - list
  - patch
  - update
  - watch
