apiVersion: dws.cray.com/v1alpha1
kind: StoragePool
metadata:
  name: dws-storagepool-test
spec:
  PoolId:           "dws-storagepool-test"
  Units:            "bytes"
  Granularity:      107374182400
  Quantity:         10
  Free:             10
