apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: storagepools.dws.cray.com
spec:
  group: dws.cray.com
  names:
    kind: StoragePool
    listKind: StoragePoolList
    plural: storagepools
    singular: storagepool
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            free:
              format: int64
              type: integer
            granularity:
              format: int64
              type: integer
            poolId:
              type: string
            quantity:
              format: int64
              type: integer
            units:
              format: int64
              type: integer
          required:
          - poolId
          - units
          - granularity
          - quantity
          - free
          type: object
        status:
          properties:
            free:
              format: int64
              type: integer
            poolId:
              type: string
            state:
              type: string
          required:
          - poolId
          - free
          - state
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
