apiVersion: dws.cray.hpe.com/v1alpha1
kind: StoragePool
metadata:
  name: dws-storagepool-test
spec:
  poolID:           "dws-storagepool-test"
  units:            "bytes"
  granularity:      "100GiB"
  quantity:         10
  free:             10
