apiVersion: dws.cray.hpe.com/v1alpha2
kind: Workflow
metadata:
  labels:
    app.kubernetes.io/name: workflow
    app.kubernetes.io/instance: workflow-sample
    app.kubernetes.io/part-of: dws-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dws-operator
  name: workflow-sample
spec:
  # TODO(user): Add fields here
