apiVersion: dws.cray.hpe.com/v1alpha1
kind: SystemConfiguration
metadata:
  name: default
spec:
  ports: [10, 20, "30-40"]
  storageNodes:
  - type: rabbit
    name: kind-worker
    computesAccess:
    - name: compute0
      index: 2
