# Use DP0 (real hardware) for the base.
resources:
- ../dp0

# Adjustments for CSM:
#  - The dws and kube-rbac-proxy images will be in the local container registry.
#  - The cert-manager is ancient, at v0.14.1.

patches:
  - patch: |-
      - op: replace
        path: /apiVersion
        value: cert-manager.io/v1alpha3
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: dws-serving-cert
  - patch: |-
      - op: replace
        path: /apiVersion
        value: cert-manager.io/v1alpha3
    target:
      group: cert-manager.io
      version: v1
      kind: Issuer
      name: dws-selfsigned-issuer

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/dataworkflowservices/dws
  newName: registry.local/dws
- name: gcr.io/kubebuilder/kube-rbac-proxy
  newName: registry.local/kube-rbac-proxy

