#!/bin/bash

DWSHOST=${DWSHOST:-localhost}
DWSPORT=${DWSPORT:-8080}
NAMESPACE=${NAMESPACE:-default}

rname=$1
[[ ! -z $rname ]] || rname="dws-workflow-test-$$"

data='{"metadata":{"name":"##RNAME##", "namespace":"##NAMESPACE##"}, "kind":"Workflow", "apiVersion":"dws.cray.hpe.com/v1alpha1", "spec":{"desiredState":"proposal", "dwDirectives":["#DW jobdw type=scratch capacity=10GiB access_mode=striped max_mds=yes","#DW stage_in type=file destination=/lus/wlm/tmp-file source=/lus/wlm/my-file","#DW stage_out type=file destination=/lus/wlm/my-file  source=/lus/wlm/tmp-file"],"jobID": 9000001, "userID": 1001, "wlmID": "5f239bd8-30db-450b-8c2c-a1a7c8631a1a"}}'

echo Creating $rname ...
jsondata=`echo $data | sed -e s:##RNAME##:$rname:g -e s:##NAMESPACE##:$NAMESPACE:g`

curl -X POST "http://${DWSHOST}:${DWSPORT}/apis/dws.cray.hpe.com/v1alpha1/namespaces/$NAMESPACE/workflows" -H "Content-Type: application/json" -d "$jsondata" | jq . || echo "Create failed"

if [ $? -eq 0 ]; then
	echo Created $rname
fi

exit $?
