#!/bin/bash

DWSHOST=${DWSHOST:-localhost}
DWSPORT=${DWSPORT:-8080}

rname=$1
[[ ! -z $rname ]] || rname="dws-workflow-test"

echo Get $rname ...
curl  -X DELETE "http://${DWSHOST}:${DWSPORT}/apis/dws.cray.com/v1alpha1/namespaces/default/workflows/${rname}" -H "Content-Type: application/json" 
