#!/bin/bash

DWSHOST=${DWSHOST:-localhost}
DWSPORT=${DWSPORT:-8080}
NAMESPACE=${NAMESPACE:-default}

rname=$1
[[ ! -z $rname ]] || rname="dws-workflow-test"

echo Get $rname ...
curl  -X DELETE "http://${DWSHOST}:${DWSPORT}/apis/dws.cray.hpe.com/v1alpha1/namespaces/$NAMESPACE/workflows/${rname}" -H "Content-Type: application/json" 
