#!/bin/bash

[[ "$1" = "all" ]] || rname=$1

DWSHOST=${DWSHOST:-localhost}
DWSPORT=${DWSPORT:-8080}
NAMESPACE=${NAMESPACE:-operators}

echo Get $rname ...
raw=`curl  -X GET -H "Content-Type: application/json" "http://${DWSHOST}:${DWSPORT}/apis/dws.cray.hpe.com/v1alpha1/namespaces/$NAMESPACE/workflows/${rname}"`

rc=`echo $raw | jq '.status' | sed -e's:\"::g'`
if [ "$rc" = "Failure" ]; then
    echo $raw | jq '.'
    exit 1
fi

if [ "$1" = "all" -o -z "$2" ]; then
    echo $raw | jq '.spec'
    echo $raw | jq '[ .status.state, .status.ready, .status.reason, .status.message, .status.drivers]'
else
    case "$2" in
    "meta")
        echo Metadata:
        echo $raw | jq '[.metadata.name, .metadata.namespace, .metadata.resourceVersion]';;
    "spec")
        echo Spec:
        echo $raw | jq '.spec';;
    "status")
        echo  "Spec:"
        echo $raw | jq '[ .spec.desiredState, .spec.dwDirectives ]'
        echo  "Status:"
        echo $raw | jq '[ .status.state, .status.ready, .status.reason, .status.message, .status.drivers]';;
    "state")
        echo  "State:"
        echo $raw | jq '[ .status.state, .status.ready, .status.reason, .status.message ]';;
    "drivers")
        echo  "State:"
        echo $raw | jq '.status.drivers';;
    esac
fi
