#!/bin/bash

DWSHOST=${DWSHOST:-localhost}
DWSPORT=${DWSPORT:-8080}
NAMESPACE=${NAMESPACE:-default}

rname=$1
[[ ! -z $rname ]] || rname="dws-workflow-test-$$"

 data='{'
data+='  "metadata": {'
data+='    "name": "##RNAME##",'
data+='    "namespace": "##NAMESPACE##"'
data+='  },'
data+='  "kind": "Workflow",'
data+='  "apiVersion": "dws.cray.hpe.com/v1alpha1",'
data+='  "spec": {'
data+='    "desiredState": "proposal",'
data+='    "dwDirectives": ['
data+='      "#DW jobdw type=scratch capacity=10GiB access_mode=striped max_mds=yes",'
data+='      "#DW tier_in template=/lus/.cray/cds/template/flash_pool source=/lus/wlm/my-file type=file",'
data+='      "#DW tier_out template=/lus/.cray/cds/template/disk_pool source=/lus/wlm/my-file type=file"'
data+='    ],'
data+='    "jobID": 9000001,'
data+='    "userID": 1001,'
data+='    "wlmID": "5f239bd8-30db-450b-8c2c-a1a7c8631a1a"'
data+='  }'
data+='}'


echo Creating $rname ...
jsondata=`echo $data | sed -e s:##RNAME##:$rname:g -e s:##NAMESPACE##:$NAMESPACE:g`

curl -X POST "http://${DWSHOST}:${DWSPORT}/apis/dws.cray.hpe.com/v1alpha1/namespaces/$NAMESPACE/workflows" -H "Content-Type: application/json" -d "$jsondata" | jq . || echo "Create failed"

if [ $? -eq 0 ]; then
    echo Created $rname 
fi

exit $?
