#!/bin/bash

[[ "$1" = "all" ]] || rname=$1

DWSHOST=${DWSHOST:-localhost}
DWSPORT=${DWSPORT:-8080}
NAMESPACE=${NAMESPACE:-operators}

echo Get $rname ...
echo curl  -X GET "http://${DWSHOST}:${DWSPORT}/apis/dws.cray.hpe.com/v1alpha1/namespaces/$NAMESPACE/workflows/${rname}/status" -H "Content-Type: application/json"
raw=`curl  -X GET "http://${DWSHOST}:${DWSPORT}/apis/dws.cray.hpe.com/v1alpha1/namespaces/$NAMESPACE/workflows/${rname}/status" -H "Content-Type: application/json"`

if [ "$1" = "all" -o "$2" = "all" ]; then
    echo $raw | jq '.'
else

    if [ -z "$2" -o  "$2" = "meta" ]; then
        echo Metadata:
        echo $raw | jq '[.metadata.name, .metadata.namespace, .metadata.resourceVersion]'
    fi

    if [ -z "$2" -o  "$2" = "spec" ]; then
        echo Spec:
        echo $raw | jq '.spec'
    fi

    if [ -z "$2" -o  "$2" = "status" ]; then
        echo  "Status:"
        echo $raw | jq '.status'
    fi
fi
