#!/bin/bash

DWSHOST=${DWSHOST:-localhost}
DWSPORT=${DWSPORT:-8080}

cwd=`dirname $0`
nthreads=$1
count=$2
rname=$3
cmd=$4

[[ -n $nthreads ]] || nthreads=10
[[ -n $count ]] || count=100
[[ -n $rname ]] || rname="workflow-test-"
[[ -n $cmd ]] || cmd=all

i=0
while [ $i -lt $nthreads ]; do
	echo Running $cwd/stress $count $rname-${i}- $cmd 
	$cwd/stress $count $rname-$i- $cmd &
	i=`expr $i + 1`
done

wait
exit 0
