#!/bin/bash

[[ "$1" = "all" ]] || rname=$1

DWSHOST=${DWSHOST:-localhost}
DWSPORT=${DWSPORT:-8080}

echo Get $rname ...
raw=`curl  -X WATCH "http://${DWSHOST}:${DWSPORT}/apis/dws.cray.com/v1alpha1/namespaces/default/workflows/${rname}" -H "Content-Type: application/json"`

echo $raw | jq '.'
