/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "stash.us.cray.com/dpm/dws-operator/pkg/apis/dws/v1alpha1"
	scheme "stash.us.cray.com/dpm/dws-operator/pkg/client/clientset/versioned/scheme"
)

// DriversGetter has a method to return a DriverInterface.
// A group's client should implement this interface.
type DriversGetter interface {
	Drivers(namespace string) DriverInterface
}

// DriverInterface has methods to work with Driver resources.
type DriverInterface interface {
	Create(*v1alpha1.Driver) (*v1alpha1.Driver, error)
	Update(*v1alpha1.Driver) (*v1alpha1.Driver, error)
	UpdateStatus(*v1alpha1.Driver) (*v1alpha1.Driver, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Driver, error)
	List(opts v1.ListOptions) (*v1alpha1.DriverList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Driver, err error)
	DriverExpansion
}

// drivers implements DriverInterface
type drivers struct {
	client rest.Interface
	ns     string
}

// newDrivers returns a Drivers
func newDrivers(c *DwsV1alpha1Client, namespace string) *drivers {
	return &drivers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the driver, and returns the corresponding driver object, and an error if there is any.
func (c *drivers) Get(name string, options v1.GetOptions) (result *v1alpha1.Driver, err error) {
	result = &v1alpha1.Driver{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("drivers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Drivers that match those selectors.
func (c *drivers) List(opts v1.ListOptions) (result *v1alpha1.DriverList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DriverList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("drivers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested drivers.
func (c *drivers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("drivers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a driver and creates it.  Returns the server's representation of the driver, and an error, if there is any.
func (c *drivers) Create(driver *v1alpha1.Driver) (result *v1alpha1.Driver, err error) {
	result = &v1alpha1.Driver{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("drivers").
		Body(driver).
		Do().
		Into(result)
	return
}

// Update takes the representation of a driver and updates it. Returns the server's representation of the driver, and an error, if there is any.
func (c *drivers) Update(driver *v1alpha1.Driver) (result *v1alpha1.Driver, err error) {
	result = &v1alpha1.Driver{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("drivers").
		Name(driver.Name).
		Body(driver).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *drivers) UpdateStatus(driver *v1alpha1.Driver) (result *v1alpha1.Driver, err error) {
	result = &v1alpha1.Driver{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("drivers").
		Name(driver.Name).
		SubResource("status").
		Body(driver).
		Do().
		Into(result)
	return
}

// Delete takes name of the driver and deletes it. Returns an error if one occurs.
func (c *drivers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("drivers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *drivers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("drivers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched driver.
func (c *drivers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Driver, err error) {
	result = &v1alpha1.Driver{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("drivers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
