/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "stash.us.cray.com/dpm/dws-operator/pkg/apis/dws/v1alpha1"
	scheme "stash.us.cray.com/dpm/dws-operator/pkg/client/clientset/versioned/scheme"
)

// DriverSpecsGetter has a method to return a DriverSpecInterface.
// A group's client should implement this interface.
type DriverSpecsGetter interface {
	DriverSpecs(namespace string) DriverSpecInterface
}

// DriverSpecInterface has methods to work with DriverSpec resources.
type DriverSpecInterface interface {
	Create(*v1alpha1.DriverSpec) (*v1alpha1.DriverSpec, error)
	Update(*v1alpha1.DriverSpec) (*v1alpha1.DriverSpec, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.DriverSpec, error)
	List(opts v1.ListOptions) (*v1alpha1.DriverSpecList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DriverSpec, err error)
	DriverSpecExpansion
}

// driverSpecs implements DriverSpecInterface
type driverSpecs struct {
	client rest.Interface
	ns     string
}

// newDriverSpecs returns a DriverSpecs
func newDriverSpecs(c *DwsV1alpha1Client, namespace string) *driverSpecs {
	return &driverSpecs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the driverSpec, and returns the corresponding driverSpec object, and an error if there is any.
func (c *driverSpecs) Get(name string, options v1.GetOptions) (result *v1alpha1.DriverSpec, err error) {
	result = &v1alpha1.DriverSpec{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("driverspecs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DriverSpecs that match those selectors.
func (c *driverSpecs) List(opts v1.ListOptions) (result *v1alpha1.DriverSpecList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DriverSpecList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("driverspecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested driverSpecs.
func (c *driverSpecs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("driverspecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a driverSpec and creates it.  Returns the server's representation of the driverSpec, and an error, if there is any.
func (c *driverSpecs) Create(driverSpec *v1alpha1.DriverSpec) (result *v1alpha1.DriverSpec, err error) {
	result = &v1alpha1.DriverSpec{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("driverspecs").
		Body(driverSpec).
		Do().
		Into(result)
	return
}

// Update takes the representation of a driverSpec and updates it. Returns the server's representation of the driverSpec, and an error, if there is any.
func (c *driverSpecs) Update(driverSpec *v1alpha1.DriverSpec) (result *v1alpha1.DriverSpec, err error) {
	result = &v1alpha1.DriverSpec{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("driverspecs").
		Name(driverSpec.Name).
		Body(driverSpec).
		Do().
		Into(result)
	return
}

// Delete takes name of the driverSpec and deletes it. Returns an error if one occurs.
func (c *driverSpecs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("driverspecs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *driverSpecs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("driverspecs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched driverSpec.
func (c *driverSpecs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DriverSpec, err error) {
	result = &v1alpha1.DriverSpec{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("driverspecs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
