/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "stash.us.cray.com/dpm/dws-operator/pkg/apis/dws/v1alpha1"
	scheme "stash.us.cray.com/dpm/dws-operator/pkg/client/clientset/versioned/scheme"
)

// DWDirectiveRuleDevesGetter has a method to return a DWDirectiveRuleDefInterface.
// A group's client should implement this interface.
type DWDirectiveRuleDevesGetter interface {
	DWDirectiveRuleDeves(namespace string) DWDirectiveRuleDefInterface
}

// DWDirectiveRuleDefInterface has methods to work with DWDirectiveRuleDef resources.
type DWDirectiveRuleDefInterface interface {
	Create(*v1alpha1.DWDirectiveRuleDef) (*v1alpha1.DWDirectiveRuleDef, error)
	Update(*v1alpha1.DWDirectiveRuleDef) (*v1alpha1.DWDirectiveRuleDef, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.DWDirectiveRuleDef, error)
	List(opts v1.ListOptions) (*v1alpha1.DWDirectiveRuleDefList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DWDirectiveRuleDef, err error)
	DWDirectiveRuleDefExpansion
}

// dWDirectiveRuleDeves implements DWDirectiveRuleDefInterface
type dWDirectiveRuleDeves struct {
	client rest.Interface
	ns     string
}

// newDWDirectiveRuleDeves returns a DWDirectiveRuleDeves
func newDWDirectiveRuleDeves(c *DwsV1alpha1Client, namespace string) *dWDirectiveRuleDeves {
	return &dWDirectiveRuleDeves{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dWDirectiveRuleDef, and returns the corresponding dWDirectiveRuleDef object, and an error if there is any.
func (c *dWDirectiveRuleDeves) Get(name string, options v1.GetOptions) (result *v1alpha1.DWDirectiveRuleDef, err error) {
	result = &v1alpha1.DWDirectiveRuleDef{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dwdirectiveruledeves").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DWDirectiveRuleDeves that match those selectors.
func (c *dWDirectiveRuleDeves) List(opts v1.ListOptions) (result *v1alpha1.DWDirectiveRuleDefList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DWDirectiveRuleDefList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("dwdirectiveruledeves").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dWDirectiveRuleDeves.
func (c *dWDirectiveRuleDeves) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("dwdirectiveruledeves").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a dWDirectiveRuleDef and creates it.  Returns the server's representation of the dWDirectiveRuleDef, and an error, if there is any.
func (c *dWDirectiveRuleDeves) Create(dWDirectiveRuleDef *v1alpha1.DWDirectiveRuleDef) (result *v1alpha1.DWDirectiveRuleDef, err error) {
	result = &v1alpha1.DWDirectiveRuleDef{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("dwdirectiveruledeves").
		Body(dWDirectiveRuleDef).
		Do().
		Into(result)
	return
}

// Update takes the representation of a dWDirectiveRuleDef and updates it. Returns the server's representation of the dWDirectiveRuleDef, and an error, if there is any.
func (c *dWDirectiveRuleDeves) Update(dWDirectiveRuleDef *v1alpha1.DWDirectiveRuleDef) (result *v1alpha1.DWDirectiveRuleDef, err error) {
	result = &v1alpha1.DWDirectiveRuleDef{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("dwdirectiveruledeves").
		Name(dWDirectiveRuleDef.Name).
		Body(dWDirectiveRuleDef).
		Do().
		Into(result)
	return
}

// Delete takes name of the dWDirectiveRuleDef and deletes it. Returns an error if one occurs.
func (c *dWDirectiveRuleDeves) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dwdirectiveruledeves").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dWDirectiveRuleDeves) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("dwdirectiveruledeves").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched dWDirectiveRuleDef.
func (c *dWDirectiveRuleDeves) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DWDirectiveRuleDef, err error) {
	result = &v1alpha1.DWDirectiveRuleDef{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("dwdirectiveruledeves").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
