/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "stash.us.cray.com/dpm/dws-operator/pkg/apis/dws/v1alpha1"
	scheme "stash.us.cray.com/dpm/dws-operator/pkg/client/clientset/versioned/scheme"
)

// StoragePoolSpecsGetter has a method to return a StoragePoolSpecInterface.
// A group's client should implement this interface.
type StoragePoolSpecsGetter interface {
	StoragePoolSpecs(namespace string) StoragePoolSpecInterface
}

// StoragePoolSpecInterface has methods to work with StoragePoolSpec resources.
type StoragePoolSpecInterface interface {
	Create(*v1alpha1.StoragePoolSpec) (*v1alpha1.StoragePoolSpec, error)
	Update(*v1alpha1.StoragePoolSpec) (*v1alpha1.StoragePoolSpec, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.StoragePoolSpec, error)
	List(opts v1.ListOptions) (*v1alpha1.StoragePoolSpecList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.StoragePoolSpec, err error)
	StoragePoolSpecExpansion
}

// storagePoolSpecs implements StoragePoolSpecInterface
type storagePoolSpecs struct {
	client rest.Interface
	ns     string
}

// newStoragePoolSpecs returns a StoragePoolSpecs
func newStoragePoolSpecs(c *DwsV1alpha1Client, namespace string) *storagePoolSpecs {
	return &storagePoolSpecs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the storagePoolSpec, and returns the corresponding storagePoolSpec object, and an error if there is any.
func (c *storagePoolSpecs) Get(name string, options v1.GetOptions) (result *v1alpha1.StoragePoolSpec, err error) {
	result = &v1alpha1.StoragePoolSpec{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("storagepoolspecs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of StoragePoolSpecs that match those selectors.
func (c *storagePoolSpecs) List(opts v1.ListOptions) (result *v1alpha1.StoragePoolSpecList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.StoragePoolSpecList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("storagepoolspecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested storagePoolSpecs.
func (c *storagePoolSpecs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("storagepoolspecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a storagePoolSpec and creates it.  Returns the server's representation of the storagePoolSpec, and an error, if there is any.
func (c *storagePoolSpecs) Create(storagePoolSpec *v1alpha1.StoragePoolSpec) (result *v1alpha1.StoragePoolSpec, err error) {
	result = &v1alpha1.StoragePoolSpec{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("storagepoolspecs").
		Body(storagePoolSpec).
		Do().
		Into(result)
	return
}

// Update takes the representation of a storagePoolSpec and updates it. Returns the server's representation of the storagePoolSpec, and an error, if there is any.
func (c *storagePoolSpecs) Update(storagePoolSpec *v1alpha1.StoragePoolSpec) (result *v1alpha1.StoragePoolSpec, err error) {
	result = &v1alpha1.StoragePoolSpec{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("storagepoolspecs").
		Name(storagePoolSpec.Name).
		Body(storagePoolSpec).
		Do().
		Into(result)
	return
}

// Delete takes name of the storagePoolSpec and deletes it. Returns an error if one occurs.
func (c *storagePoolSpecs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("storagepoolspecs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *storagePoolSpecs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("storagepoolspecs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched storagePoolSpec.
func (c *storagePoolSpecs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.StoragePoolSpec, err error) {
	result = &v1alpha1.StoragePoolSpec{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("storagepoolspecs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
