/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "stash.us.cray.com/dpm/dws-operator/pkg/apis/dws/v1alpha1"
	scheme "stash.us.cray.com/dpm/dws-operator/pkg/client/clientset/versioned/scheme"
)

// WorkflowSpecsGetter has a method to return a WorkflowSpecInterface.
// A group's client should implement this interface.
type WorkflowSpecsGetter interface {
	WorkflowSpecs(namespace string) WorkflowSpecInterface
}

// WorkflowSpecInterface has methods to work with WorkflowSpec resources.
type WorkflowSpecInterface interface {
	Create(*v1alpha1.WorkflowSpec) (*v1alpha1.WorkflowSpec, error)
	Update(*v1alpha1.WorkflowSpec) (*v1alpha1.WorkflowSpec, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.WorkflowSpec, error)
	List(opts v1.ListOptions) (*v1alpha1.WorkflowSpecList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.WorkflowSpec, err error)
	WorkflowSpecExpansion
}

// workflowSpecs implements WorkflowSpecInterface
type workflowSpecs struct {
	client rest.Interface
	ns     string
}

// newWorkflowSpecs returns a WorkflowSpecs
func newWorkflowSpecs(c *DwsV1alpha1Client, namespace string) *workflowSpecs {
	return &workflowSpecs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the workflowSpec, and returns the corresponding workflowSpec object, and an error if there is any.
func (c *workflowSpecs) Get(name string, options v1.GetOptions) (result *v1alpha1.WorkflowSpec, err error) {
	result = &v1alpha1.WorkflowSpec{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("workflowspecs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of WorkflowSpecs that match those selectors.
func (c *workflowSpecs) List(opts v1.ListOptions) (result *v1alpha1.WorkflowSpecList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.WorkflowSpecList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("workflowspecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested workflowSpecs.
func (c *workflowSpecs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("workflowspecs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a workflowSpec and creates it.  Returns the server's representation of the workflowSpec, and an error, if there is any.
func (c *workflowSpecs) Create(workflowSpec *v1alpha1.WorkflowSpec) (result *v1alpha1.WorkflowSpec, err error) {
	result = &v1alpha1.WorkflowSpec{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("workflowspecs").
		Body(workflowSpec).
		Do().
		Into(result)
	return
}

// Update takes the representation of a workflowSpec and updates it. Returns the server's representation of the workflowSpec, and an error, if there is any.
func (c *workflowSpecs) Update(workflowSpec *v1alpha1.WorkflowSpec) (result *v1alpha1.WorkflowSpec, err error) {
	result = &v1alpha1.WorkflowSpec{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("workflowspecs").
		Name(workflowSpec.Name).
		Body(workflowSpec).
		Do().
		Into(result)
	return
}

// Delete takes name of the workflowSpec and deletes it. Returns an error if one occurs.
func (c *workflowSpecs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("workflowspecs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *workflowSpecs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("workflowspecs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched workflowSpec.
func (c *workflowSpecs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.WorkflowSpec, err error) {
	result = &v1alpha1.WorkflowSpec{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("workflowspecs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
