apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: system
spec:
  replicas: 1
  template:
  spec:
    containers:
    - name: webhook
      env:
      - name: ENVIRONMENT
        value: "kind"