# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/dws.cray.hpe.com_workflows.yaml
- bases/dws.cray.hpe.com_dwdirectiverules.yaml
- bases/dws.cray.hpe.com_storagepools.yaml
- bases/dws.cray.hpe.com_directivebreakdowns.yaml
- bases/dws.cray.hpe.com_computes.yaml
- bases/dws.cray.hpe.com_servers.yaml
- bases/dws.cray.hpe.com_storages.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_workflows.yaml
#- patches/webhook_in_dwdirectiverules.yaml
#- patches/webhook_in_storagepools.yaml
#- patches/webhook_in_directivebreakdowns.yaml
#- patches/webhook_in_computes.yaml
#- patches/webhook_in_servers.yaml
#- patches/webhook_in_storages.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_workflows.yaml
#- patches/cainjection_in_dwdirectiverules.yaml
#- patches/cainjection_in_storagepools.yaml
#- patches/cainjection_in_directivebreakdowns.yaml
#- patches/cainjection_in_computes.yaml
#- patches/cainjection_in_servers.yaml
#- patches/cainjection_in_storages.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
