# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/dataworkflowservices.github.io_workflows.yaml
- bases/dataworkflowservices.github.io_dwdirectiverules.yaml
- bases/dataworkflowservices.github.io_directivebreakdowns.yaml
- bases/dataworkflowservices.github.io_computes.yaml
- bases/dataworkflowservices.github.io_servers.yaml
- bases/dataworkflowservices.github.io_storages.yaml
- bases/dataworkflowservices.github.io_clientmounts.yaml
- bases/dataworkflowservices.github.io_persistentstorageinstances.yaml
- bases/dataworkflowservices.github.io_systemconfigurations.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- path: patches/webhook_in_workflows.yaml
- path: patches/webhook_in_dwdirectiverules.yaml
- path: patches/webhook_in_directivebreakdowns.yaml
- path: patches/webhook_in_computes.yaml
- path: patches/webhook_in_servers.yaml
- path: patches/webhook_in_storages.yaml
- path: patches/webhook_in_clientmounts.yaml
- path: patches/webhook_in_persistentstorageinstances.yaml
- path: patches/webhook_in_systemconfigurations.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- path: patches/cainjection_in_workflows.yaml
- path: patches/cainjection_in_dwdirectiverules.yaml
- path: patches/cainjection_in_directivebreakdowns.yaml
- path: patches/cainjection_in_computes.yaml
- path: patches/cainjection_in_servers.yaml
- path: patches/cainjection_in_storages.yaml
- path: patches/cainjection_in_clientmounts.yaml
- path: patches/cainjection_in_persistentstorageinstances.yaml
- path: patches/cainjection_in_systemconfigurations.yaml
#- path: patches/cainjection_in_clientmounts.yaml
#- path: patches/cainjection_in_computes.yaml
#- path: patches/cainjection_in_dwdirectiverules.yaml
#- path: patches/cainjection_in_directivebreakdowns.yaml
#- path: patches/cainjection_in_persistentstorageinstances.yaml
#- path: patches/cainjection_in_servers.yaml
#- path: patches/cainjection_in_storages.yaml
#- path: patches/cainjection_in_systemconfigurations.yaml
#- path: patches/cainjection_in_workflows.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
