# Please refer to https://stash.us.cray.com/projects/CLOUD/repos/cray-charts/browse/stable/cray-service/values.yaml?at=refs%2Fheads%2Fmaster
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")

cray-service:
  nameOverride: dws-operator
  type: Deployment
  service:
    enabled: False
  replicaCount: 1
  serviceAccountName: dws-operator
  containers:
    cray-dws-operator:
      name: dws-operator
      image:
        repository: cray/cray-dws-operator
      env:
      - name: WATCH_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: OPERATOR_NAME
        value: dws-operator
  nodeSelector:
    cray.dpm.dg.dpm-management-node: "true"

global:
  appVersion: "" # This is set at build time.
  # these are values to address shortcomings of helm in referencing .Chart.* values in sub-charts/parent charts:
  # https://github.com/helm/helm/issues/4314
  # https://github.com/helm/helm/issues/3920
  chart:
    name: "" # set at deploy time automatically, no need to ever set explicitly
    version: "" # set at deploy time automatically, no need to ever set explicitly

